// Local, network-free Figma authoring plugin. Creates only namespaced proposal nodes.
const RUN = 'Zeimee FDE / Illustrated 04';
const TARGET_PAGE = '3192:60';
const C = {paper:'#FFFFFF',white:'#FFFFFF',ink:'#152632',muted:'#727888',line:'#DEE1E7',blue:'#534DFF',pale:'#F6F6F7',ice:'#EEF2FF',dark:'#152632',onDark:'#FFFFFF',hover:'#4111FF',sky:'#8DBBFF'};
const S={created:[],mutated:[],vars:{},styles:{},roots:{},sections:{},step:0,buttons:{}};
const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const paint=k=>S.vars[k]?[figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb(C[k])},'color',S.vars[k])]:[{type:'SOLID',color:rgb(C[k]||k)}];
const record=n=>(S.created.push(n.id),n);
function al(parent,name,w,dir='VERTICAL',gap=0,pad=0,bg){const n=record(figma.createFrame());n.name=name;n.layoutMode=dir;n.primaryAxisSizingMode='AUTO';n.counterAxisSizingMode='FIXED';n.resize(w,1);n.itemSpacing=gap;n.paddingLeft=n.paddingRight=n.paddingTop=n.paddingBottom=pad;n.fills=bg?paint(bg):[];n.clipsContent=false;if(parent)parent.appendChild(n);n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='HUG';return n;}
function tx(parent,text,size=16,w=300,style='Regular',color='ink',family='LINE Seed JP',lh=1.85){const n=record(figma.createText());n.name=text.replace(/\n/g,' / ').slice(0,60);n.fontName={family:S.fontFamily,style};n.fontSize=size;n.lineHeight={unit:'PIXELS',value:Math.round(size*lh)};n.letterSpacing={unit:'PERCENT',value:size>=32?-2:0};n.characters=text;n.fills=paint(color);n.textAutoResize='HEIGHT';n.resize(w,Math.ceil(size*lh));parent.appendChild(n);n.layoutSizingHorizontal='FIXED';n.layoutSizingVertical='HUG';const key=`${family}/${style}/${size}/${Math.round(size*lh)}`;return n;}
function rect(parent,name,w,h,color='line'){const n=record(figma.createRectangle());n.name=name;n.resize(w,h);n.fills=paint(color);parent.appendChild(n);return n;}
function rule(parent,w,color='line'){return rect(parent,'Editorial rule',w,1,color);}
function spacer(parent,h){const n=al(parent,'Breathing space',1);n.resize(1,h);n.layoutSizingVertical='FIXED';return n;}
function illustration(parent,name,w,h,key='fieldwork'){const n=rect(parent,name,w,h);n.fills=[{type:'IMAGE',imageHash:S.images[key],scaleMode:'FIT'}];return n;}
function label(parent,text,w=300,color='muted'){return tx(parent,text,12,w,'Bold',color,'LINE Seed JP',1.5);}
function arrow(parent,size=24,color='ink'){const n=record(figma.createNodeFromSvg(`<svg width="${size}" height="${size}" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M4 12H20M13 5L20 12L13 19" fill="none" stroke="${C[color]}" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`));n.name='Arrow / right';parent.appendChild(n);return n;}
async function logo(parent,w=146,dark=false){const orig=await figma.getNodeByIdAsync(dark?'3208:61':'3208:77');const fonts=orig.findAllWithCriteria({types:['TEXT']}).flatMap(n=>n.getStyledTextSegments(['fontName']).map(s=>s.fontName));await Promise.all(fonts.map(f=>figma.loadFontAsync(f)));const n=record(orig.createInstance());parent.appendChild(n);n.rescale(w/n.width);n.name='Zeimee / existing wordmark';return n;}
function section(root,key,w,pad=72,bg='paper',gap=40){const n=al(root,key,w,'VERTICAL',gap,pad,bg);S.sections[key]=n.id;return n;}
function button(parent,text,w=288,kind='Primary'){const base=S.buttons[kind];const n=record(base.createInstance());parent.appendChild(n);n.setProperties({[S.buttonLabel]:text});n.resize(w,64);n.layoutSizingHorizontal='FIXED';const t=n.findOne(n=>n.name==='Label');if(t)t.resize(w-96,t.height);return n;}
function headerLine(parent,kicker,title,w,mobile=false,color='ink'){const wrap=al(parent,'Section heading',w,'VERTICAL',mobile?24:40);label(wrap,kicker,w,color==='onDark'?'onDark':'muted');tx(wrap,title,mobile?31:46,w,'Bold',color,'LINE Seed JP',1.5);return wrap;}
async function init(){const page=await figma.getNodeByIdAsync(TARGET_PAGE);await figma.setCurrentPageAsync(page);const exists=page.children.find(n=>n.name===RUN+' / Desktop');if(exists)throw Error('Proposal already exists. Run the current open plugin only; do not duplicate.');const available=await figma.listAvailableFontsAsync();S.fontFamily=['LINE Seed JP_OTF','LINE Seed JP','LINE Seed JP_TTF'].find(f=>['Regular','Bold'].every(s=>available.some(x=>x.fontName.family===f&&x.fontName.style===s)));if(!S.fontFamily)throw Error('LINE Seed JP Regular / Bold are required. Install the official font and relaunch Figma.');await Promise.all(['Regular','Bold'].map(style=>figma.loadFontAsync({family:S.fontFamily,style})));S.images={fieldwork:figma.createImage(figma.base64Decode(FIELDWORK_B64)).hash,review:figma.createImage(figma.base64Decode(REVIEW_B64)).hash};
const primitives=figma.variables.createVariableCollection(RUN+' / Primitives');const semantic=figma.variables.createVariableCollection(RUN+' / Semantic');S.collections=[primitives.id,semantic.id];
for(const [k,val] of Object.entries(C)){const p=figma.variables.createVariable(k,primitives,'COLOR');p.scopes=[];p.setValueForMode(primitives.defaultModeId,rgb(val));p.setVariableCodeSyntax('WEB',`var(--fde-${k})`);const v=figma.variables.createVariable('color/'+k,semantic,'COLOR');v.scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR'];v.setValueForMode(semantic.defaultModeId,{type:'VARIABLE_ALIAS',id:p.id});v.setVariableCodeSyntax('WEB',`var(--fde-color-${k})`);S.vars[k]=v;}
for(const val of [0,8,12,16,24,32,40,48,64,72,96]){const v=figma.variables.createVariable('space/'+val,semantic,'FLOAT');v.scopes=['GAP'];v.setValueForMode(semantic.defaultModeId,val);v.setVariableCodeSyntax('WEB',`var(--fde-space-${val})`);S.vars['space'+val]=v;}
const styleDefs=[['Display / PC',66,1.45,'Bold'],['Display / Mobile',36,1.55,'Bold'],['Heading / Large',46,1.5,'Bold'],['Heading / Medium',32,1.5,'Bold'],['Heading / Mobile',31,1.5,'Bold'],['Body / Large',18,1.9,'Regular'],['Body',16,1.85,'Regular'],['Label',12,1.5,'Bold']];
for(const [name,size,lh,weight] of styleDefs){const st=figma.createTextStyle();st.name=RUN+' / '+name;st.fontName={family:S.fontFamily,style:weight};st.fontSize=size;st.lineHeight={unit:'PIXELS',value:Math.round(size*lh)};st.letterSpacing={unit:'PERCENT',value:size>=32?-2:0};S.styles[`LINE Seed JP/${weight}/${size}/${Math.round(size*lh)}`]=st.id;}
const x=Math.max(...page.children.map(n=>n.x+n.width),0)+320;S.x=x;const d=al(page,RUN+' / Desktop',1440,'VERTICAL',0,0,'paper');d.x=x;d.y=200;d.clipsContent=true;S.roots.desktop=d.id;const m=al(page,RUN+' / Mobile',390,'VERTICAL',0,0,'paper');m.x=x+1580;m.y=200;m.clipsContent=true;S.roots.mobile=m.id;
const guide=al(page,RUN+' / Design direction',1440,'VERTICAL',32,64,'white');guide.x=x;guide.y=-850;headerLine(guide,'DESIGN PROPOSAL 04  /  2026.09.08','現場を知る。仕組みをつくる。',1312);tx(guide,'会計士・税理士事務所のためのFDE。\n細い人物線画、白い余白、整った日本語で、伴走する専門性を伝える。',22,1160,'Regular');const row=al(guide,'Palette',1312,'HORIZONTAL',24);for(const key of ['paper','ink','blue','sky','pale']){const cell=al(row,key,235,'VERTICAL',12);rect(cell,key,235,64,key);label(cell,key+'  '+C[key],235);}tx(guide,'参考の役割：Takram＝文字組みと余白 / Work & Co＝支援工程 / Ramp＝業務の動き / LayerX＝配色\n採用素材：最後の人物線画2点。書体：LINE Seed JP（見出しBold / 本文Regular）。実績・効果の数値は仮置きしない。',14,1312);S.roots.guide=guide.id;
const kit=al(page,RUN+' / Button components',620,'VERTICAL',28,48,'white');kit.x=x+2150;kit.y=200;S.roots.kit=kit.id;tx(kit,'相談への入口',28,524,'Bold');tx(kit,'LP専用の相談ボタン。横幅可変 / ラベル編集可。\nPrimary・Hover・Inverseの3状態。',14,524);figma.currentPage.selection=[guide];figma.viewport.scrollAndZoomIntoView([guide]);}

async function makeButton(){const kit=await figma.getNodeByIdAsync(S.roots.kit);const variants=[];for(const [i,kind] of ['Primary','Hover','Inverse'].entries()){const c=record(figma.createComponent());c.name='State='+kind;c.layoutMode='HORIZONTAL';c.primaryAxisSizingMode='FIXED';c.counterAxisSizingMode='FIXED';c.primaryAxisAlignItems='SPACE_BETWEEN';c.counterAxisAlignItems='CENTER';c.resize(320,64);for(const field of ['paddingLeft','paddingRight'])c.setBoundVariable(field,S.vars.space24);for(const field of ['paddingTop','paddingBottom'])c.setBoundVariable(field,S.vars.space16);c.setBoundVariable('itemSpacing',S.vars.space24);c.fills=paint(kind==='Inverse'?'white':kind==='Hover'?'hover':'blue');const t=tx(c,'事務所の課題を相談する',15,228,'Bold',kind==='Inverse'?'ink':'white','LINE Seed JP',1.5);t.name='Label';arrow(c,24,kind==='Inverse'?'ink':'white');variants.push(c);S.buttons[kind]=c;}
const set=record(figma.combineAsVariants(variants,kit));set.name=RUN+' / Consultation button';set.layoutMode='VERTICAL';set.itemSpacing=20;set.paddingTop=set.paddingRight=set.paddingBottom=set.paddingLeft=20;set.fills=[];set.primaryAxisSizingMode='AUTO';set.counterAxisSizingMode='AUTO';S.buttonLabel=set.addComponentProperty('Label','TEXT','事務所の課題を相談する');for(const c of variants){c.findOne(n=>n.name==='Label').componentPropertyReferences={characters:S.buttonLabel};c.description='Zeimee FDE LP consultation call to action. Editable Label. Minimum height 64px.';}S.buttonSet=set.id;figma.currentPage.selection=[kit];figma.viewport.scrollAndZoomIntoView([kit]);}

async function hero(mobile=false){const root=await figma.getNodeByIdAsync(S.roots[mobile?'mobile':'desktop']);const w=mobile?390:1440,p=mobile?24:72,cw=w-p*2;const nav=al(root,(mobile?'M':'D')+' / Navigation',w,'HORIZONTAL',24,p,'paper');nav.paddingTop=nav.paddingBottom=mobile?24:28;nav.counterAxisAlignItems='CENTER';nav.primaryAxisAlignItems='SPACE_BETWEEN';await logo(nav,mobile?118:146);if(mobile){const b=al(nav,'Menu button / 44px target',48,'VERTICAL',6,12);rule(b,24,'ink');rule(b,24,'ink');b.paddingTop=b.paddingBottom=16;}else{const links=al(nav,'Navigation links',700,'HORIZONTAL',32);links.primaryAxisAlignItems='SPACE_BETWEEN';links.counterAxisAlignItems='CENTER';label(links,'私たちの役割',104,'ink');label(links,'できること',90,'ink');label(links,'進め方',66,'ink');button(links,'相談する',224);}
const s=section(root,(mobile?'M':'D')+' / Hero',w,p,'paper',mobile?32:44);s.paddingTop=mobile?24:48;s.paddingBottom=mobile?56:64;label(s,'会計士・税理士事務所に特化したFDE',cw,'blue');const row=al(s,'Hero copy',cw,mobile?'VERTICAL':'HORIZONTAL',mobile?28:64);const title=mobile?'会計の現場から、\n仕事のしくみを\n変える。':'会計の現場から、\n仕事のしくみを変える。';tx(row,title,mobile?36:66,mobile?cw:884,'Bold','ink','LINE Seed JP',mobile?1.55:1.45);const intro=al(row,'Service introduction',mobile?cw:348,'VERTICAL',24);if(!mobile)spacer(intro,56);tx(intro,'事務所ごとに違う業務へ。\n設計から実装、定着まで。',mobile?17:18,mobile?cw:348,'Bold','ink','LINE Seed JP',1.9);tx(intro,'Zeimeeのエンジニアが現場を理解し、\n日々の仕事に使える仕組みをつくります。',14,mobile?cw:348);if(mobile)button(intro,'事務所の課題を相談する',cw);else{const link=al(intro,'Consultation link',348,'HORIZONTAL',24);label(link,'事務所の課題を相談する',252,'ink');arrow(link);rule(intro,348,'ink');}
illustration(s,'Fieldwork / abstract people illustration',cw,mobile?228:480);const caption=al(s,'Illustration caption',cw,mobile?'VERTICAL':'HORIZONTAL',12);caption.primaryAxisAlignItems='SPACE_BETWEEN';label(caption,'仕組みは、現場から。',mobile?cw:440,'ink');label(caption,'FIELDWORK  /  DESIGN  /  ENGINEERING',mobile?cw:350);figma.currentPage.selection=[s];figma.viewport.scrollAndZoomIntoView([s]);}

async function introduction(mobile=false){const root=await figma.getNodeByIdAsync(S.roots[mobile?'mobile':'desktop']);const w=mobile?390:1440,p=mobile?24:72,cw=w-p*2;const s=section(root,(mobile?'M':'D')+' / Our role',w,p,'white',mobile?32:56);s.paddingTop=s.paddingBottom=mobile?72:112;const row=al(s,'Role introduction',cw,mobile?'VERTICAL':'HORIZONTAL',mobile?28:80);label(row,'01  /  私たちの役割',mobile?cw:260);const body=al(row,'Role statement',mobile?cw:956,'VERTICAL',32);tx(body,'いつもの仕事を、\nもっとよくする技術を。',mobile?31:46,mobile?cw:956,'Bold','ink','LINE Seed JP',1.5);tx(body,'資料を集める。転記する。確かめる。\nその繰り返しの奥に、事務所ごとの工夫と判断があります。\n私たちはまず、その仕事を知ることから始めます。',mobile?16:18,mobile?cw:820,'Regular','ink','LINE Seed JP',1.9);rule(body,mobile?cw:956);const detail=al(body,'FDE definition',mobile?cw:956,mobile?'VERTICAL':'HORIZONTAL',mobile?16:48);tx(detail,'FDEとは',18,mobile?cw:172,'Bold');tx(detail,'エンジニアが業務の現場に入り、課題の整理から設計・開発・運用改善まで取り組む支援のかたちです。現場で使われるところまで、一緒につくります。',16,mobile?cw:736);label(body,'Forward Deployed Engineering',mobile?cw:500,'blue');figma.currentPage.selection=[s];figma.viewport.scrollAndZoomIntoView([s]);}

const THEMES=[{title:'資料を、\n使える情報に。',body:'届き方も、形式もばらばらな資料。\n受け取り方から読取・整理までを見直し、\n次の作業に使える状態へ整えます。',tags:'証憑の受領・整理 / データ化 / 明細との紐付け',foot:'資料の入口から、仕事の流れを整える。'},{title:'事務所の判断を、\n仕組みに。',body:'過去の仕訳や事務所のルールをもとに、\nAIが候補をつくり、人が確かめる。\n経験の蓄積を、日々の仕事に生かします。',tags:'ルールの整理 / 仕訳候補の生成 / レビュー設計',foot:'AIの候補に、人の確かな判断を。'},{title:'分断した仕事を、\nつなぎ直す。',body:'Excel、会計ソフト、ファイル保管。\nその間にある転記や確認を見つめ直し、\n月次の仕事を一つの流れにします。',tags:'データの連携 / 転記の見直し / 月次業務の整備',foot:'いまある道具を生かし、業務をつなぐ。'}];
function documentMock(parent,w,mobile=false){const panel=al(parent,'Illustration / received documents',w,'VERTICAL',24,mobile?24:48,'pale');label(panel,'資料の整理  /  EXAMPLE',w-(mobile?48:96));const file=al(panel,'Editable invoice sample',w-(mobile?48:96),'VERTICAL',16,24,'white');label(file,'SAMPLE  /  請求書',w-(mobile?96:144),'blue');tx(file,'請求内容を、確認しやすく。',mobile?17:22,w-(mobile?96:144),'Bold');rule(file,w-(mobile?96:144));for(const [a,b] of [['発行日','読取済み'],['請求金額','読取済み'],['取引内容','確認対象']]){const r=al(file,'Field / '+a,w-(mobile?96:144),'HORIZONTAL',16);r.primaryAxisAlignItems='SPACE_BETWEEN';label(r,a,mobile?86:180);label(r,b,80,b==='確認対象'?'blue':'ink');}label(panel,'受領 → 読取 → 内容をそろえる',w-(mobile?48:96),'ink');return panel;}
function reviewMock(parent,w,mobile=false){const p=mobile?24:48;const panel=al(parent,'Illustration / review workflow',w,'VERTICAL',24,p,'ice');label(panel,'仕訳レビュー  /  EXAMPLE',w-p*2);const card=al(panel,'Review candidate',w-p*2,'VERTICAL',20,24,'white');label(card,'AIによる候補',w-p*2-48,'blue');tx(card,'候補と根拠を、ひと目で。',mobile?18:24,w-p*2-48,'Bold');rule(card,w-p*2-48);const r=al(card,'Candidate account',w-p*2-48,'HORIZONTAL',16);label(r,'勘定科目',mobile?86:152);tx(r,'消耗品費',16,mobile?130:180,'Bold');label(card,'参照：過去の仕訳・事務所のルール',w-p*2-48);const confirm=al(card,'Human review status',w-p*2-48,'HORIZONTAL',16,16,'pale');label(confirm,'人が確認して、承認',w-p*2-80,'ink');label(panel,'候補をつくる → 根拠を見る → 人が判断',w-p*2,'ink');return panel;}
function flowMock(parent,w,mobile=false){const p=mobile?24:48;const panel=al(parent,'Illustration / connected workflow',w,'VERTICAL',22,p,'pale');label(panel,'月次業務のつながり  /  EXAMPLE',w-p*2);for(const [num,title,sub] of [['01','受け取る','証憑・明細・顧問先からの資料'],['02','整える','データの形式・事務所のルール'],['03','確認して、次へ','レビュー・会計ソフトへの取込']]){const r=al(panel,'Workflow / '+num,w-p*2,'HORIZONTAL',20,20,'white');label(r,num,26,'blue');const text=al(r,'Step details',w-p*2-86,'VERTICAL',4);tx(text,title,18,w-p*2-86,'Bold');tx(text,sub,12,w-p*2-86,'Regular','muted','LINE Seed JP',1.5);}return panel;}
async function themes(mobile=false){const root=await figma.getNodeByIdAsync(S.roots[mobile?'mobile':'desktop']);const w=mobile?390:1440,p=mobile?24:72,cw=w-p*2;const s=section(root,(mobile?'M':'D')+' / What we change',w,p,'paper',mobile?48:72);s.paddingTop=s.paddingBottom=mobile?72:112;headerLine(s,'02  /  できること','変えられるのは、\n入力作業だけではありません。',cw,mobile);for(const [i,item] of THEMES.entries()){rule(s,cw);const row=al(s,'Theme '+(i+1),cw,mobile?'VERTICAL':'HORIZONTAL',mobile?32:80);const copy=al(null,'Theme '+(i+1)+' / Editorial copy',mobile?cw:560,'VERTICAL',28);label(copy,'0'+(i+1),mobile?cw:560,'blue');tx(copy,item.title,mobile?31:38,mobile?cw:560,'Bold','ink','LINE Seed JP',1.5);tx(copy,item.body,16,mobile?cw:560);label(copy,item.tags,mobile?cw:560);const visualHolder=al(null,'Theme '+(i+1)+' / Visual',mobile?cw:656,'VERTICAL',16);[documentMock,reviewMock,flowMock][i](visualHolder,mobile?cw:656,mobile);label(visualHolder,item.foot,mobile?cw:656,'ink');if(mobile||i===1){row.appendChild(copy);row.appendChild(visualHolder);}else{row.appendChild(visualHolder);row.appendChild(copy);}if(!mobile)copy.paddingTop=20;}tx(s,'上記は取り組みの例です。対象業務・連携方法は、事務所の環境を確認して設計します。',12,cw,'Regular','muted','LINE Seed JP',1.8);figma.currentPage.selection=[s];figma.viewport.scrollAndZoomIntoView([s]);}

const PROCESS=[['01','現場を知る','資料、使っている道具、日々の判断。\nいまの仕事の流れを一緒に整理します。'],['02','進め方を決める','取り組む業務と、確かめたい変化を定め、\n小さく試せる範囲から設計します。'],['03','つくり、確かめる','実際の業務に照らして試作と検証を重ね、\n使いながら形にしていきます。'],['04','定着させ、育てる','運用の手順を整え、使う人の声をもとに、\n改善を続けます。']];
async function process(mobile=false){const root=await figma.getNodeByIdAsync(S.roots[mobile?'mobile':'desktop']);const w=mobile?390:1440,p=mobile?24:72,cw=w-p*2;const s=section(root,(mobile?'M':'D')+' / How we work',w,p,'white',mobile?40:64);s.paddingTop=s.paddingBottom=mobile?72:112;headerLine(s,'03  /  進め方','となりで考え、\n動くところまで。',cw,mobile,'ink');const row=al(s,'Collaboration and process',cw,mobile?'VERTICAL':'HORIZONTAL',mobile?40:80);const left=al(row,'Human review illustration',mobile?cw:536,'VERTICAL',16);illustration(left,'Human review / abstract person illustration',mobile?cw:536,mobile?300:420,'review');tx(left,'業務を理解する。つくる。\n使われるまで、伴走する。',mobile?22:28,mobile?cw:536,'Bold','ink','LINE Seed JP',1.6);const list=al(row,'Our process',mobile?cw:680,'VERTICAL',24);for(const [num,title,body]of PROCESS){rule(list,mobile?cw:680,'line');const r=al(list,title,mobile?cw:680,'HORIZONTAL',mobile?16:32);label(r,num,32,'ink');const b=al(r,'Step description',mobile?cw-48:616,'VERTICAL',12);tx(b,title,mobile?22:26,mobile?cw-48:616,'Bold','ink','LINE Seed JP',1.5);tx(b,body,mobile?14:16,mobile?cw-48:616,'Regular','ink');}figma.currentPage.selection=[s];figma.viewport.scrollAndZoomIntoView([s]);}

const FAQ=[['何から相談すればよいですか？','「資料の整理に時間がかかる」「転記が多い」など、いま困っている仕事からお聞かせください。課題の整理からご一緒します。'],['いま使っている会計ソフトでも相談できますか？','現在のソフトやExcel、資料の受け取り方を確認したうえで、連携や運用の方法を検討します。'],['AIがすべて自動で判断するのですか？','AIによる候補の生成と、人による確認・承認を組み合わせて設計します。対象業務に合う確認の流れを大切にします。']];
async function closing(mobile=false){const root=await figma.getNodeByIdAsync(S.roots[mobile?'mobile':'desktop']);const w=mobile?390:1440,p=mobile?24:72,cw=w-p*2;const faq=section(root,(mobile?'M':'D')+' / Questions',w,p,'white',40);faq.paddingTop=faq.paddingBottom=mobile?64:104;label(faq,'04  /  よくあるご質問',cw);for(const [i,item]of FAQ.entries()){rule(faq,cw);const r=al(faq,'FAQ '+(i+1),cw,mobile?'VERTICAL':'HORIZONTAL',mobile?20:64);tx(r,item[0],mobile?18:22,mobile?cw:480,'Bold');tx(r,item[1],16,mobile?cw:752);}const s=section(root,(mobile?'M':'D')+' / Contact',w,p,'blue',mobile?36:48);s.paddingTop=s.paddingBottom=mobile?80:112;label(s,'まずは、お話ししませんか。',cw,'white');tx(s,mobile?'いま、時間が\nかかっている\nその仕事から。':'いま、時間がかかっている\nその仕事から。',mobile?36:56,cw,'Bold','white','LINE Seed JP',1.5);tx(s,'事務所の現場に合う仕組みを、\n一緒に考えるところから始めましょう。',16,cw,'Regular','white');button(s,'事務所の課題を相談する',mobile?cw:360,'Inverse');const f=section(root,(mobile?'M':'D')+' / Footer',w,p,'paper',32);f.paddingTop=f.paddingBottom=48;const r=al(f,'Footer identity',cw,mobile?'VERTICAL':'HORIZONTAL',32);r.primaryAxisAlignItems='SPACE_BETWEEN';await logo(r,146);label(r,'株式会社Zeimee',mobile?cw:250,'ink');rule(f,cw);const r2=al(f,'Footer legal',cw,mobile?'VERTICAL':'HORIZONTAL',16);r2.primaryAxisAlignItems='SPACE_BETWEEN';label(r2,'会社情報   /   プライバシーポリシー',mobile?cw:600);label(r2,'© Zeimee Inc.',mobile?cw:200);figma.currentPage.selection=[s];figma.viewport.scrollAndZoomIntoView([s]);}

async function motionBoard(){const page=figma.currentPage;const board=al(page,RUN+' / Motion direction',1440,'VERTICAL',40,64,'white');board.x=S.x+2150;board.y=1100;S.roots.motion=board.id;headerLine(board,'MOTION STUDY  /  演出の方向性','動きは、仕事の変化を伝えるために。',1312);tx(board,'スクロールで資料から確認へ進む、3つの状態。人物線画や文字の登場は静かに。\n背景の幾何学模様ではなく、業務を理解できる動きに絞る。',18,1200);const r=al(board,'Workflow storyboard',1312,'HORIZONTAL',32);for(const [i,title]of ['資料を受け取る','候補と根拠が見える','人が確かめる'].entries()){const cell=al(r,'State '+(i+1),416,'VERTICAL',20);label(cell,'0'+(i+1)+'  /  '+title,416,'blue');const card=al(cell,'Motion state',416,'VERTICAL',24,32,i===0?'pale':'ice');label(card,'EXAMPLE',352);tx(card,i===0?'請求書・領収書':i===1?'AIによる候補':'確認して、承認',26,352,'Bold');rule(card,352);tx(card,i===0?'形式をそろえて、\n次の作業に使える状態へ。':i===1?'過去の仕訳とルールを参照。\n候補と根拠を並べて確認。':'承認する前に、人が判断。\n確かめた情報を次の仕事へ。',16,352);label(cell,i===0?'スクロールで資料が整列':i===1?'候補と根拠を順に表示':'確認対象を控えめに強調',416);}
rule(board,1312);tx(board,'動きの仕様案',24,1000,'Bold');tx(board,'・見出し：行ごとに12px上昇 + フェード、450ms。日本語の可読性を優先。\n・業務デモ：3段階をスクロールで切り替え。表示内容を常に読める状態にする。\n・ボタン：背景色と矢印が180msで変化。キーボードのフォーカスを明示。\n・スマホ：縦の流れで同じ意味を表現。reduce motionでは全情報を静止表示。',16,1250);tx(board,'このボードは動きの絵コンテです。スクロール演出そのものは、この静止デザインでは再生しません。',12,1250,'Regular','muted');figma.currentPage.selection=[board];figma.viewport.scrollAndZoomIntoView([board]);}

async function audit(){const issues=[];for(const key of ['desktop','mobile']){const root=await figma.getNodeByIdAsync(S.roots[key]);const nodes=root.findAll(()=>true);for(const n of nodes){if(n.type==='TEXT'&&(!n.characters||n.width<5||n.hasMissingFont))issues.push({id:n.id,reason:'text'});if(n.parent&&n.parent.type==='FRAME'&&n.parent.layoutMode!=='NONE'&&n.layoutPositioning!=='ABSOLUTE'&&(n.x+n.width>n.parent.width+1||n.x< -1))issues.push({id:n.id,reason:'horizontal overflow',name:n.name});}S.mutated.push(root.id);}S.audit=issues;const summary=al(figma.currentPage,RUN+' / Handoff',620,'VERTICAL',24,48,'white');summary.x=S.x+2150;summary.y=2500;S.roots.handoff=summary.id;tx(summary,'デザイン案 / 04',30,524,'Bold');tx(summary,'PC 1440px / Mobile 390px\nLINE Seed JP / Regular・Bold\n編集可能なテキスト・図・オートレイアウト\nロゴは既存コンポーネントを使用\n人物イラストはオリジナルの生成PNG（線画）',16,524);tx(summary,'レビューするポイント\n1. 線画の抽象度・余白・文字組みの印象\n2. FDE支援として伝わるか\n3. 相談につながる情報の順番',16,524);tx(summary,'公開前：イラストの最終選定、最終コピーとリンク先の確認。\nこの案は本番公開していません。',12,524,'Regular','muted');const d=await figma.getNodeByIdAsync(S.roots.desktop);figma.currentPage.selection=[d];figma.viewport.scrollAndZoomIntoView([d]);return issues;}

const STEPS=[['1. Foundations',init],['2. Button',makeButton],['3. Desktop hero',()=>hero(false)],['4. Desktop role',()=>introduction(false)],['5. Desktop themes',()=>themes(false)],['6. Desktop process',()=>process(false)],['7. Desktop closing',()=>closing(false)],['8. Mobile hero',()=>hero(true)],['9. Mobile role',()=>introduction(true)],['10. Mobile themes',()=>themes(true)],['11. Mobile process',()=>process(true)],['12. Mobile closing',()=>closing(true)],['13. Motion direction',motionBoard],['14. Validation',audit]];
figma.showUI('<style>body{font:13px system-ui;padding:16px;color:#202020}button{padding:12px 16px;border:0;background:#202020;color:white;cursor:pointer}pre{white-space:pre-wrap;font-size:11px;max-height:280px;overflow:auto}</style><strong>Zeimee FDE / Illustrated 04</strong><p id="status">Approved line illustrations · LINE Seed JP · blue-violet palette</p><button id="next">Build illustrated proposal</button> <button id="done">Close</button><pre id="log"></pre><script>document.getElementById("next").onclick=()=>parent.postMessage({pluginMessage:{type:"build"}},"*");document.getElementById("done").onclick=()=>parent.postMessage({pluginMessage:{type:"close"}},"*");onmessage=e=>{const m=e.data.pluginMessage;if(!m)return;document.getElementById("status").textContent=m.status;document.getElementById("log").textContent=m.log||"";document.getElementById("next").disabled=m.busy||m.finished;};</script>',{width:540,height:440,themeColors:false});
let building=false;
async function buildProposal(){if(building)return;building=true;try{while(S.step<STEPS.length){const step=STEPS[S.step];figma.ui.postMessage({status:step[0]+' — working',busy:true});await step[1]();S.step++;figma.commitUndo();}figma.ui.postMessage({status:'Illustrated 04 — complete',finished:true,log:JSON.stringify({step:S.step,roots:S.roots,sections:S.sections,nodeCount:S.created.length,audit:S.audit,fontFamily:S.fontFamily},null,2)});}catch(e){figma.ui.postMessage({status:'Error: '+e.message,log:String(e.stack),busy:false});}finally{building=false;}};

figma.ui.onmessage=async m=>{if(m.type==='close'){figma.closePlugin();return;}if(m.type==='build')await buildProposal();};
// Launch directly so generation does not depend on the plugin iframe controls.
buildProposal();
